name: Github Actions tests

on:
  push:
    branches:
    - main

jobs:
  check_veda_status:
    name: Check API status
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Check Veda Status
      run: curl https://veda.jesulayomi.tech/api/status

    - name: Check GatherGo Status
      run: curl https://gathergo.jesulayomi.tech/api/status

    - name: Check SCHub Status
      run: curl https://schub-api.jesulayomi.tech/api/status
